query getTodosByCategory($input: GetTodosByCategory!) {
  getTodosByCategory(input: $input) {
    id
    title
    done
    priority
  }
}

query getTodosByUser($input: GetTodosByUser!) {
  getTodosByUser(input: $input) {
    id
    category
    title
    done
    priority
  }
}

mutation updateTodoDone($input: UpdateTodoDone!) {
  updateTodoDone(input: $input)
}

mutation copyTodo($input: CopyTodo!) {
  copyTodo(input: $input)
}

mutation deleteTodo($input: DeleteTodo!) {
  deleteTodo(input: $input)
}

mutation createTodo($input: NewTodo!) {
  createTodo(input: $input)
}

mutation updateTodo($input: UpdateTodo!) {
  updateTodo(input: $input)
}
