query getTodosByCategory($input: GetTodosByCategory!) {
  getTodosByCategory(input: $input) {
    id
    title
    done
    priority
  }
}

query getTodosByUser($input: GetTodosByUser!) {
  getTodosByUser(input: $input) {
    id
    category
    title
    done
    priority
  }
}

mutation updateTodoDone($input: UpdateTodoDone!) {
  updateTodoDone(input: $input)
}
